// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brqqzwzjutztsknlkqwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycXF6d3pqdXR6dHNrbmxrcXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjQ2MjEsImV4cCI6MjA3MTgwMDYyMX0.L6D1akbbJQ3gS8z2WLXcS6cXdGl1IjUgyp7ZKnOAeRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});