// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chbntbekbgetbyyxapqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoYm50YmVrYmdldGJ5eXhhcHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTM5NDcsImV4cCI6MjA3MjUyOTk0N30.iTlMXOoynJFKE0djf0LAZoaeLY6O07uYM5UxtS8jcDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);